apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: fastapi-backend
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi-backend
        tier: backend
    spec:
      containers:
      - name: fastapi-backend
        image: fastapi-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mongo-root-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mongo-root-password
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database_url
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database_name
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database_port
